/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksObjectPageObjectPage journey");

        opaTest("Navigate to BooksObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheBooksList.onFilterBar().iExecuteSearch();

            Then.onTheBooksList.onTable().iCheckRows();
            When.onTheBooksList.onTable().iPressRow(0);

            Then.onTheBooksObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBooksObjectPage.iCheckNumberOfSections(2);
            When.onTheBooksObjectPage.iPressSectionIconTabFilterButton("Identification");
            Then.onTheBooksObjectPage.iCheckSection({ section: "Identification" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "title" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "description" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "publishedAt" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "availability" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "genre" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "price" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "effectivePrice" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "stock" });
            Then.onTheBooksObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "status" });
            When.onTheBooksObjectPage.iPressSectionIconTabFilterButton("author::Identification");
            Then.onTheBooksObjectPage.iCheckSection({ section: "author::Identification" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "name" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "country" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "businessId" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "address_street" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "address_city" });
            Then.onTheBooksObjectPage.onForm({ section: "author::Identification" }).iCheckField({ property: "address_zipCode" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});