namespace smart.notifications;

using {
    cuid,
    managed
} from '@sap/cds/common';

// Bring in Library entities we associate to.
// This is why monorepo Layout A shines — one `using` and we share
// the domain model with the Library service.
using {smart.library.Books}                  from './schema';
using {smart.library.Lending.Members}        from './schema';


// ─────────────────────────────────────────────────────────────
// Notifications context — event-driven notifications for the
// Library domain. Populated by cds.on() handlers in
// notifications-srv/notifications-service.js when the Library
// service emits BookBorrowed / BookReturned events.
// ─────────────────────────────────────────────────────────────
context Notifications {

    // ─── Enum types ───

    // Who receives a Notification row.
    // MEMBER = the borrower (per-user notification, `member` FK is set)
    // ADMIN  = admin dashboard row  (`member` is null — no admin entity exists)
    type RecipientType : String(20) enum {
        MEMBER;
        ADMIN;
    }


    // ─── Entity 1: RawEvents (immutable event log) ───
    //
    // Every event received from Library is logged here first.
    // The `eventId` field has a UNIQUE constraint — this is the
    // idempotency mechanism: a 2nd delivery of the same event
    // fails on INSERT and we skip processing.
    //
    // Rows here are IMMUTABLE except for `processedAt` and
    // `processingError` (updated after downstream processing).
    entity RawEvents : cuid {

        // The event's own UUID, generated by the emitter (Library).
        // UNIQUE — the deduplication mechanism.
        @assert.unique
        eventId         : String(36) not null;

        // e.g., "BookBorrowed", "BookReturned"
        eventType       : String(50) not null;

        // Full event payload as JSON string.
        // Kept for audit + potential replay.
        payload         : LargeString;

        // When the notification service received the event.
        receivedAt      : Timestamp not null;

        // When the derived Notifications rows were successfully
        // created + mock-delivered. Null = still pending / failed.
        processedAt     : Timestamp;

        // If the handler threw, the error message lands here.
        // Enables debugging without hunting through logs.
        processingError : String(1000);
    }


    // ─── Entity 2: Notifications (user-facing derived records) ───
    //
    // For each incoming event the handler creates 1-N Notifications
    // rows (fan-out): one per recipient. E.g., BookBorrowed produces
    // 2 rows — one for the borrower (recipientType=MEMBER, member set),
    // one for admin (recipientType=ADMIN, member=null).
    //
    // Uses `managed` for automatic createdAt/createdBy/modifiedAt.
    entity Notifications : cuid, managed {

        // Which kind of recipient — drives handler logic, UI filtering.
        recipientType : RecipientType not null;

        // FK to the specific member for MEMBER rows.
        // Null for ADMIN rows (no admin entity exists in this project).
        // Provides referential integrity for member notifications.
        member        : Association to Members;

        // e.g., "BorrowConfirmation", "ReturnConfirmation",
        //       "AdminBorrowAlert", "AdminReturnAlert"
        type          : String(50) not null;

        // Short one-line summary shown in list/table.
        title         : String(200) not null;

        // Longer body text — shown in detail view or notification tray.
        message       : String(500);

        // Link back to the book this notification is about.
        // Uses the shared Library.Books entity (monorepo win).
        relatedBook   : Association to Books;

        // Traceability: which event produced this notification?
        // Enables answering "why did I get this?" in support scenarios.
        sourceEvent   : Association to RawEvents;

        // Read state — user marks it read via markAsRead action later.
        isRead        : Boolean default false;
        readAt        : Timestamp;
    }
}